# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require 'euler2'

describe 'Problem 2' do
  it 'can find all the Fibonacci numbers up to 11' do
    expect(fibs_to(11)).to eq [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]
  end
end