# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require 'euler2'

describe 'Problem 2' do
  it 'finds the first number in the sequence' do
    expect(fibs_to(1)).to eq [1]
  end

it 'finds the first two numbers in the sequence' do
    expect(fibs_to(2)).to eq [1, 2]
  end

it 'finds the first two numbers in the sequence' do
    expect(fibs_to(3)).to eq [1, 2, 3]
  end

end